In [2]:
import numpy as np
import pandas as pd
import os

import matplotlib.pyplot as plt

In [3]:
os.listdir()

['ExploringData.ipynb',
 '.DS_Store',
 'readme.md',
 '.gitignore',
 'test.txt',
 '.ipynb_checkpoints',
 '.git',
 'Data']

In [4]:
basedir = os.getcwd()
datadir = basedir + "/Data"

In [5]:
os.listdir(datadir)

['otu_annotation.csv',
 '.DS_Store',
 'archive',
 'microbiome_data.csv',
 'sample_desc_deid.csv']

In [12]:
data = pd.read_csv(datadir + '/microbiome_data.csv', index_col = 0)
OTUref = pd.read_csv(datadir + '/otu_annotation.csv', index_col = 0)
sample_desc = pd.read_csv(datadir + '/sample_desc_deid.csv', index_col = 0)

In [7]:
data

,1001360178,1000106028,1000160068,1001406208,1000606198,1000105048,1000603178,1000601248,1000860248,1000101018,...,1005503278.rs,1004302338.rs,1900701418.rs,1004704138.rs,1004602368.rs,NTC52,1002101188.rs,1000101168.rs,NTC51,1002204158.rs
OTUId,,,,,,,,,,,,,,,,,,,,,
OTU_25,1152,306,459,586,1468,3,1,0,1245,0,...,0,4,0,0,0,0,0,0,0,0
OTU_38,367,1091,727,328,58,29,0,2,15,0,...,0,0,0,0,0,0,0,0,0,0
OTU_233,0,0,0,959,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
OTU_962,55,20,17,32,71,0,0,0,67,0,...,0,0,0,0,0,0,0,0,0,0
OTU_168,0,0,0,0,0,24,0,0,0,2,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
OTU_1764,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
OTU_1854,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
OTU_1803,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
OTU_1593,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
OTU_1382,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
OTUref

,Kingdom,Phylum,Class,Order,Family,Genus,Species
OTUId,,,,,,,
OTU_25,Bacteria,Actinobacteria,Actinobacteria,Actinomycetales,Propionibacteriaceae,Propionibacterium,acnes
OTU_38,Bacteria,Firmicutes,Bacilli,Bacillales,Staphylococcaceae,Staphylococcus,epidermidis
OTU_233,Bacteria,Actinobacteria,Actinobacteria,Actinomycetales,Propionibacteriaceae,Propionibacterium,acnes
OTU_962,Bacteria,Actinobacteria,Actinobacteria,Actinomycetales,Propionibacteriaceae,Propionibacterium,acnes
OTU_168,Bacteria,Firmicutes,Clostridia,Clostridiales,NaN,NaN,NaN
...,...,...,...,...,...,...,...
OTU_1764,Bacteria,Proteobacteria,Deltaproteobacteria,Myxococcales,0319-6G20,NaN,NaN
OTU_1854,Bacteria,Bacteroidetes,Bacteroidia,Bacteroidales,Prevotellaceae,Prevotella,NaN
OTU_1803,Bacteria,Firmicutes,Clostridia,Clostridiales,Ruminococcaceae,NaN,NaN
OTU_1593,Bacteria,NaN,NaN,NaN,NaN,NaN,NaN
OTU_1382,Bacteria,Firmicutes,Clostridia,Clostridiales,Ruminococcaceae,NaN,NaN

In [13]:
sample_desc

,BarcodeSequence,LinkerPrimerSequence,BodySite,SubjectID,GestDayColl,GestWeekColl,TrimColl,intra_ut_fetal_demise,History_of_preterm_delivery,Withdrew,...,Number_of_babies,Race,Ethnicity,ReversePrimer,Saliva_volume_uL,Note_any_concerns_regarding_the_specimen,Run_No,Number_within_run,Bead_Beating_Time,Description
#SampleID,,,,,,,,,,,,,,,,,,,,,
1000201108,AACGCACGCTAG,GCACTCCTACGGGAGGCAGCA,Vaginal_Swab,10002,81.0,12.0,1.0,F,NaN,T,...,NaN,White,Hispanic,CGTATCGCCTCCCTCGCGCCATCAG,NaN,Patient did not complete a specimen log,run001,1,NaN,1
1000501278,AACTCGTCGATG,GCACTCCTACGGGAGGCAGCA,Vaginal_Swab,10005,188.0,27.0,3.0,F,0.0,F,...,1.0,Asian-Japanese,Non-hispanic,CGTATCGCCTCCCTCGCGCCATCAG,NaN,Specimen log not provided,run001,2,NaN,2
1000101018,AACTGTGCGTAC,GCACTCCTACGGGAGGCAGCA,Vaginal_Swab,10001,-73.0,-9.0,0.0,T,NaN,F,...,NaN,White,Non-hispanic,CGTATCGCCTCCCTCGCGCCATCAG,NaN,0,run001,3,NaN,3
1000101028,AAGAGATGTCGA,GCACTCCTACGGGAGGCAGCA,Vaginal_Swab,10001,-65.0,-8.0,0.0,T,NaN,F,...,NaN,White,Non-hispanic,CGTATCGCCTCCCTCGCGCCATCAG,NaN,0,run001,4,NaN,4
1000201118,AAGCTGCAGTCG,GCACTCCTACGGGAGGCAGCA,Vaginal_Swab,10002,86.0,13.0,1.0,F,NaN,T,...,NaN,White,Hispanic,CGTATCGCCTCCCTCGCGCCATCAG,NaN,Patient did not complete a specimen log,run001,5,NaN,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1010104488.rs,GTCTGACAGTTG,GCACTCCTACGGGAGGCAGCA,Tooth_Gum,10101,311.0,45.0,4.0,F,1.0,F,...,1.0,White,Non-hispanic,CGTATCGCCTCCCTCGCGCCATCAG,NaN,0,run018,287,NaN,4398
1002402218.ca2.rs,GTCTGGATAGCG,GCACTCCTACGGGAGGCAGCA,Stool,10024,150.0,22.0,2.0,F,0.0,F,...,1.0,White,Non-hispanic,CGTATCGCCTCCCTCGCGCCATCAG,NaN,0,run018,288,15 min,4399
1002302248.bn1.rs,GTCTTCGTCGCT,GCACTCCTACGGGAGGCAGCA,Stool,10023,169.0,25.0,2.0,F,0.0,F,...,1.0,White,Hispanic,CGTATCGCCTCCCTCGCGCCATCAG,NaN,0,run018,289,15 min,4400
1002102208.ak2.rs,GTGACCTGATGT,GCACTCCTACGGGAGGCAGCA,Stool,10021,139.0,20.0,2.0,F,0.0,F,...,1.0,White,Hispanic,CGTATCGCCTCCCTCGCGCCATCAG,NaN,0,run018,290,15 min,4401
NTC52.rs,GTGTCTACATTG,GCACTCCTACGGGAGGCAGCA,NTC,NTC,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,CGTATCGCCTCCCTCGCGCCATCAG,NaN,NaN,run018,291,NaN,4402